/* -*- Mode: C++; tab-width: 4; indent-tabs-mode: nil; c-basic-offset: 2 -*- */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#ifndef WEBGLMETHODDISPATCHER_H_
#define WEBGLMETHODDISPATCHER_H_

#include "TexUnpackBlob.h"
#include "WebGLCrossProcessCommandQueue.h"
#include "HostWebGLContext.h"
#include "WebGLPcqParamTraits.h"

namespace mozilla {

// The WebGLMethodDispatcher will dispatch commands read from the
// HostWebGLCommandSink and issue them to a given HostWebGLContext.
DECLARE_METHOD_DISPATCHER(WebGLMethodDispatcher, HostWebGLCommandSink, HostWebGLContext)

// Defines each method the WebGLMethodDispatcher handles.  The COUNTER value
// is used as a cross-process ID for each of the methods. 
#define DEFINE_METHOD_HELPER(_METHOD, _SYNC) \
  DEFINE_METHOD_DISPATCHER(WebGLMethodDispatcher, __COUNTER__, _METHOD, _SYNC)
#define DEFINE_ASYNC(_METHOD) DEFINE_METHOD_HELPER(_METHOD, CommandSyncType::ASYNC)
#define DEFINE_SYNC(_METHOD)  DEFINE_METHOD_HELPER(_METHOD, CommandSyncType::SYNC)

DEFINE_SYNC(HostWebGLContext::IsContextLost)
DEFINE_ASYNC(HostWebGLContext::Disable)
DEFINE_ASYNC(HostWebGLContext::Enable)
DEFINE_SYNC(HostWebGLContext::IsEnabled)
DEFINE_ASYNC(HostWebGLContext::SetContextOptions)
DEFINE_SYNC(HostWebGLContext::SetDimensionsImpl)
DEFINE_SYNC(HostWebGLContext::GetSupportedExtensionsImpl)
DEFINE_SYNC(HostWebGLContext::GetParameterImpl)
DEFINE_ASYNC(HostWebGLContext::AttachShader)
DEFINE_ASYNC(HostWebGLContext::BindAttribLocationImpl)
DEFINE_ASYNC(HostWebGLContext::BindFramebuffer)
DEFINE_ASYNC(HostWebGLContext::BindRenderbuffer)
DEFINE_ASYNC(HostWebGLContext::BlendColor)
DEFINE_ASYNC(HostWebGLContext::BlendEquation)
DEFINE_ASYNC(HostWebGLContext::BlendEquationSeparate)
DEFINE_ASYNC(HostWebGLContext::BlendFunc)
DEFINE_ASYNC(HostWebGLContext::BlendFuncSeparate)
DEFINE_SYNC(HostWebGLContext::CheckFramebufferStatus)
DEFINE_ASYNC(HostWebGLContext::Clear)
DEFINE_ASYNC(HostWebGLContext::ClearColor)
DEFINE_ASYNC(HostWebGLContext::ClearDepth)
DEFINE_ASYNC(HostWebGLContext::ClearStencil)
DEFINE_ASYNC(HostWebGLContext::ColorMask)
DEFINE_ASYNC(HostWebGLContext::CompileShader)
DEFINE_SYNC(HostWebGLContext::CreateFramebufferImpl)
DEFINE_SYNC(HostWebGLContext::CreateProgramImpl)
DEFINE_SYNC(HostWebGLContext::CreateRenderbufferImpl)
DEFINE_SYNC(HostWebGLContext::CreateShaderImpl)
DEFINE_ASYNC(HostWebGLContext::CullFace)
DEFINE_ASYNC(HostWebGLContext::DeleteFramebuffer)
DEFINE_ASYNC(HostWebGLContext::DeleteProgram)
DEFINE_ASYNC(HostWebGLContext::DeleteRenderbuffer)
DEFINE_ASYNC(HostWebGLContext::DeleteShader)
DEFINE_ASYNC(HostWebGLContext::DepthFunc)
DEFINE_ASYNC(HostWebGLContext::DepthMask)
DEFINE_ASYNC(HostWebGLContext::DepthRange)
DEFINE_ASYNC(HostWebGLContext::DetachShader)
DEFINE_ASYNC(HostWebGLContext::Flush)
DEFINE_SYNC(HostWebGLContext::Finish)
DEFINE_ASYNC(HostWebGLContext::FramebufferRenderbuffer)
DEFINE_ASYNC(HostWebGLContext::FramebufferTexture2D)
DEFINE_ASYNC(HostWebGLContext::FrontFace)
DEFINE_SYNC(HostWebGLContext::GetActiveAttribImpl)
DEFINE_SYNC(HostWebGLContext::GetActiveUniformImpl)
DEFINE_SYNC(HostWebGLContext::GetAttachedShadersImpl)
DEFINE_SYNC(HostWebGLContext::GetAttribLocationImpl)
DEFINE_SYNC(HostWebGLContext::GetBufferParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetError)
DEFINE_SYNC(HostWebGLContext::GetFramebufferAttachmentParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetProgramParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetProgramInfoLogImpl)
DEFINE_SYNC(HostWebGLContext::GetRenderbufferParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetShaderParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetShaderPrecisionFormatImpl)
DEFINE_SYNC(HostWebGLContext::GetShaderInfoLogImpl)
DEFINE_SYNC(HostWebGLContext::GetShaderSourceImpl)
DEFINE_SYNC(HostWebGLContext::GetUniformImpl)
DEFINE_SYNC(HostWebGLContext::GetUniformLocationImpl)
DEFINE_ASYNC(HostWebGLContext::Hint)
DEFINE_ASYNC(HostWebGLContext::LineWidth)
DEFINE_ASYNC(HostWebGLContext::LinkProgram)
DEFINE_ASYNC(HostWebGLContext::PixelStorei)
DEFINE_ASYNC(HostWebGLContext::PolygonOffset)
DEFINE_ASYNC(HostWebGLContext::SampleCoverage)
DEFINE_ASYNC(HostWebGLContext::Scissor)
DEFINE_ASYNC(HostWebGLContext::ShaderSourceImpl)
DEFINE_ASYNC(HostWebGLContext::StencilFunc)
DEFINE_ASYNC(HostWebGLContext::StencilFuncSeparate)
DEFINE_ASYNC(HostWebGLContext::StencilMask)
DEFINE_ASYNC(HostWebGLContext::StencilMaskSeparate)
DEFINE_ASYNC(HostWebGLContext::StencilOp)
DEFINE_ASYNC(HostWebGLContext::StencilOpSeparate)
DEFINE_ASYNC(HostWebGLContext::Viewport)
DEFINE_ASYNC(HostWebGLContext::BindBuffer)
DEFINE_ASYNC(HostWebGLContext::BindBufferBase)
DEFINE_ASYNC(HostWebGLContext::BindBufferRange)
DEFINE_SYNC(HostWebGLContext::CreateBufferImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteBuffer)
DEFINE_ASYNC(HostWebGLContext::CopyBufferSubData)
DEFINE_ASYNC(HostWebGLContext::GetBufferSubDataImpl)
DEFINE_ASYNC(HostWebGLContext::BufferDataImpl)
DEFINE_ASYNC(HostWebGLContext::BufferSubDataImpl)
DEFINE_ASYNC(HostWebGLContext::BlitFramebuffer)
DEFINE_ASYNC(HostWebGLContext::FramebufferTextureLayer)
DEFINE_ASYNC(HostWebGLContext::InvalidateFramebufferImpl)
DEFINE_ASYNC(HostWebGLContext::InvalidateSubFramebufferImpl)
DEFINE_ASYNC(HostWebGLContext::ReadBuffer)
DEFINE_SYNC(HostWebGLContext::GetInternalformatParameterImpl)
DEFINE_ASYNC(HostWebGLContext::RenderbufferStorage_base)
DEFINE_ASYNC(HostWebGLContext::ActiveTexture)
DEFINE_ASYNC(HostWebGLContext::BindTexture)
DEFINE_ASYNC(HostWebGLContext::CreateTextureImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteTexture)
DEFINE_ASYNC(HostWebGLContext::GenerateMipmap)
DEFINE_ASYNC(HostWebGLContext::CopyTexImage2D)
DEFINE_ASYNC(HostWebGLContext::TexStorage)
DEFINE_ASYNC(HostWebGLContext::TexImageImpl)
DEFINE_ASYNC(HostWebGLContext::TexSubImageImpl)
DEFINE_ASYNC(HostWebGLContext::CompressedTexImageImpl)
DEFINE_ASYNC(HostWebGLContext::CompressedTexSubImageImpl)
DEFINE_ASYNC(HostWebGLContext::CopyTexSubImage)
DEFINE_SYNC(HostWebGLContext::GetTexParameterImpl)
DEFINE_ASYNC(HostWebGLContext::TexParameter_base)
DEFINE_ASYNC(HostWebGLContext::UseProgram)
DEFINE_ASYNC(HostWebGLContext::ValidateProgram)
DEFINE_SYNC(HostWebGLContext::GetFragDataLocationImpl)
DEFINE_ASYNC(HostWebGLContext::UniformNfv)
DEFINE_ASYNC(HostWebGLContext::UniformNiv)
DEFINE_ASYNC(HostWebGLContext::UniformNuiv)
DEFINE_ASYNC(HostWebGLContext::UniformMatrixAxBfv)
DEFINE_ASYNC(HostWebGLContext::UniformFVec)
DEFINE_ASYNC(HostWebGLContext::UniformIVec)
DEFINE_ASYNC(HostWebGLContext::UniformUIVec)
DEFINE_ASYNC(HostWebGLContext::VertexAttrib4f)
DEFINE_ASYNC(HostWebGLContext::VertexAttribI4i)
DEFINE_ASYNC(HostWebGLContext::VertexAttribI4ui)
DEFINE_ASYNC(HostWebGLContext::VertexAttribDivisor)
DEFINE_SYNC(HostWebGLContext::GetIndexedParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetUniformIndicesImpl)
DEFINE_SYNC(HostWebGLContext::GetActiveUniformsImpl)
DEFINE_SYNC(HostWebGLContext::GetUniformBlockIndexImpl)
DEFINE_SYNC(HostWebGLContext::GetActiveUniformBlockParameterImpl)
DEFINE_SYNC(HostWebGLContext::GetActiveUniformBlockNameImpl)
DEFINE_ASYNC(HostWebGLContext::UniformBlockBinding)
DEFINE_ASYNC(HostWebGLContext::EnableVertexAttribArray)
DEFINE_ASYNC(HostWebGLContext::DisableVertexAttribArray)
DEFINE_SYNC(HostWebGLContext::GetVertexAttribImpl)
DEFINE_SYNC(HostWebGLContext::GetVertexAttribOffset)
DEFINE_ASYNC(HostWebGLContext::VertexAttribAnyPointer)
DEFINE_ASYNC(HostWebGLContext::ClearBufferfvImpl)
DEFINE_ASYNC(HostWebGLContext::ClearBufferivImpl)
DEFINE_ASYNC(HostWebGLContext::ClearBufferuivImpl)
DEFINE_ASYNC(HostWebGLContext::ClearBufferfi)
DEFINE_ASYNC(HostWebGLContext::ReadPixels1)
DEFINE_ASYNC(HostWebGLContext::ReadPixels2)
DEFINE_SYNC(HostWebGLContext::CreateSamplerImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteSampler)
DEFINE_ASYNC(HostWebGLContext::BindSampler)
DEFINE_ASYNC(HostWebGLContext::SamplerParameteri)
DEFINE_ASYNC(HostWebGLContext::SamplerParameterf)
DEFINE_SYNC(HostWebGLContext::GetSamplerParameterImpl)
DEFINE_SYNC(HostWebGLContext::FenceSyncImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteSync)
DEFINE_SYNC(HostWebGLContext::ClientWaitSync)
DEFINE_ASYNC(HostWebGLContext::WaitSync)
DEFINE_SYNC(HostWebGLContext::GetSyncParameterImpl)
DEFINE_SYNC(HostWebGLContext::CreateTransformFeedbackImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteTransformFeedback)
DEFINE_ASYNC(HostWebGLContext::BindTransformFeedback)
DEFINE_ASYNC(HostWebGLContext::BeginTransformFeedback)
DEFINE_ASYNC(HostWebGLContext::EndTransformFeedback)
DEFINE_ASYNC(HostWebGLContext::PauseTransformFeedback)
DEFINE_ASYNC(HostWebGLContext::ResumeTransformFeedback)
DEFINE_ASYNC(HostWebGLContext::TransformFeedbackVaryingsImpl)
DEFINE_SYNC(HostWebGLContext::GetTransformFeedbackVaryingImpl)
DEFINE_ASYNC(HostWebGLContext::EnableExtensionImpl)
DEFINE_ASYNC(HostWebGLContext::EnqueueError)
DEFINE_ASYNC(HostWebGLContext::EnqueueWarning)
DEFINE_ASYNC(HostWebGLContext::DrawBuffersImpl)
DEFINE_SYNC(HostWebGLContext::GetASTCExtensionSupportedProfilesImpl)
DEFINE_SYNC(HostWebGLContext::GetTranslatedShaderSourceImpl)
DEFINE_ASYNC(HostWebGLContext::LoseContext)
DEFINE_SYNC(HostWebGLContext::MOZDebugGetParameterImpl)
DEFINE_ASYNC(HostWebGLContext::RestoreContext)
DEFINE_ASYNC(HostWebGLContext::BindVertexArray)
DEFINE_SYNC(HostWebGLContext::CreateVertexArrayImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteVertexArray)
DEFINE_ASYNC(HostWebGLContext::DrawArraysInstanced)
DEFINE_ASYNC(HostWebGLContext::DrawElementsInstanced)
DEFINE_SYNC(HostWebGLContext::CreateQueryImpl)
DEFINE_ASYNC(HostWebGLContext::DeleteQuery)
DEFINE_ASYNC(HostWebGLContext::BeginQuery)
DEFINE_ASYNC(HostWebGLContext::EndQuery)
DEFINE_ASYNC(HostWebGLContext::QueryCounter)
DEFINE_SYNC(HostWebGLContext::GetQueryImpl)
DEFINE_SYNC(HostWebGLContext::GetQueryParameterImpl)

#undef DEFINE_METHOD_HELPER
#undef DEFINE_ASYNC
#undef DEFINE_SYNC

}  // namespace mozilla

#endif // WEBGLMETHODDISPATCHER_H_
